### ISSUE TITLE
The "ProtoC" task failed unexpectedly

### ISSUE THREAD

**Issue by meghma** [warrenfalk/msbuild-protocol-buffers#4]
I have had a build task for a long time that started failing suddenly. If is for compiling a protobuf file. I am not sure how to fix / troubleshoot this. Using VS 2022.
Please help?
```
Severity    Code    Description Project File    Line    Suppression State
Error   MSB4018 The "ProtoC" task failed unexpectedly.
System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2, String path3, String path4)
   at MsBuild.ProtocolBuffers.ProtoC.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()     <local path>\.nuget\packages\msbuild.protocolbuffers\1.1.0\build\MsBuild.ProtocolBuffers.targets    52 
```

**Comment by meghma** [comment]
I will try with Grpc.tools

**Comment by warrenfalk** [comment]
I was just coming here to stay that this project is defunct ever since Grpc.Tools was released. Just use that.
